---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /Portfolio/templates index.html $DEPLOYPATH
    - /Portfolio/static -R img $DEPLOYPATH
    - /Portfolio/static -R files $DEPLOYPATH